'use strict';
var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

/**
 * patient model file
 * autogenerated by mongoose-scaffold-crud
 */

var DoctorsSchema = new Schema({
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    department: String,
    availableRoundward: [{type: mongoose.Schema.Types.ObjectId, ref: 'Roundward', dropDups: true}]
});

module.exports = mongoose.model('Doctor', DoctorsSchema);